spring:
  application:
    name: api-gateway
  config:
    import:
      - optional:configserver:http://localhost:8888/

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: payment-authorization
          uri: lb://payment-authorization
          predicates:
            - Path=/api/v1/authorize/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080