server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alejo2075/card-payment-processor-config
          clone-on-start: true


